### ISSUE TITLE
What does R04 mean?

### ISSUE THREAD

**Issue by gymgym1212** [dirkriehle/amos-course#1]
@dirkriehle Hi Dr. Dirk Riehle, I've come across some doubts in my recent reading about your slides. There are always some footnotes after the title as shown in the figure below, but I don't know what it means. I would appreciate it if you could answer me!

<img width="1167" alt="image" src="https://user-images.githubusercontent.com/37684061/115415046-27cc6e80-a229-11eb-953d-ddcc2621a4f4.png">

**Comment by dirkriehle** [comment]
The patterned notation [R04] is common among computer scientists and represents an index into a bibliography. The square brackets indicate that the value, R04, is to be seen as the index. In my case, you can find the bibliography, where you can look up R04, at https://amos.uni1.de (usually, but may have changed in the meantime).
